name: "QA Test"

#trigger manually
on: workflow_dispatch

jobs:
  build:
    name: "build"
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.3"

  test:
    name: "Test"
    needs: [build]
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.2"