name: Sonar Code Test

on: 
     workflow_call:
          inputs:
               version:
                    required: true
                    type: string

jobs:

     sonar-code-scan:
          runs-on: ubuntu-latest
          steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
               fetch-depth: 0
            
          - name: "Prepare Composition Action"
            uses: ./.github/actions/prepare
            with:
              version: ${{inputs.version}}

          - name: "Restore the cache"
            id: cache
            uses: actions/cache@v4
            with:
               path: ./vendor
               key: ${{ github.sha }}-php-vendor-cache

          - name: "Install composer"
            if: steps.cache.outputs.cache-hit != 'true'
            run: |
               composer install

          - name: Set up SonarQube Scanner
            uses: sonarsource/sonarcloud-github-action@v2.3.0
            env:
               GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
               SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


