name: "Test Laraval App"

on: 
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  test:
      name: "Test the app"
      runs-on: ubuntu-latest
      services:
        mysql: 
          image: mysql:latest
          ports:
            - 3306:3306
          env:
            MYSQL_DATABASE: test
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: false

      steps:

        - name: "Checkout"
          uses: actions/checkout@v4

        - name: "Prepare Composition Action"
          uses: ./.github/prepare/action.yaml
          with:
            version: ${{inputs.version}}

        - name: "Restore the cache"
          id: cache
          uses: actions/cache@v4
          with:
            path: ./vendor
            key: ${{ github.sha }}-php-vendor-cache

        - name: "Install composer"
          if: steps.cache.outputs.cache-hit != 'true'
          run: |
            composer install
            
        - name: "Setup env"
          run: |
            cp .env.ci .env

        - name: "Migrate the DB"
          run: |
            php artisan migrate

        - name: "Run Unit Tests"
          run: |
            php artisan test